my_server/__init__.py
from flask import Flask
from my_server.config import Config
from my_server.main.routes import main

app = Flask(__name__)

app.config.from_object(Config)

app.register_blueprint(main)

from my_server import error

my_server/main/routes.py
from flask import Blueprint, redirect, render_template, url_for, abort, flash, request, session
from my_server import db_handler as dbh

main = Blueprint('main',__name__, template_folder='templates')

# Main employee list
@main.route('/')
@main.route('/index')
def index():
    values = 'employed.name, employed.phone_nr, department.name'
    table = 'employed JOIN department ON employed.department = department.dept_id'
    employees = dbh.select_sql(values, table)
    if not employees:
        abort(500)
    return render_template('index.html', employees=employees)

# List employees
@main.route('/employees')
def list_empl():
    employees = dbh.select_sql('employed.name, department.name, id', 'employed JOIN department ON employed.department = department.dept_id')
    return render_template('list_empl.html', employees = employees)

@main.route('/employees', methods=['POST'])
def list_empl_post():
    session['update_empl'] = request.form['id']
    return url_for('main.update_empl')

# List departments
@main.route('/departments', methods=['GET'])
def list_dept():
    departments = dbh.select_sql('name, dept_id', 'department')
    return render_template('list_dept.html', departments = departments)

@main.route('/departments', methods=['POST'])
def list_dept_post():
    session['update_dept'] = request.form['id']
    return url_for('main.update_dept')

# Add employee
@main.route('/add-employee')
def add_empl():
    departments = dbh.select_sql('name, dept_id','department')
    employees = dbh.select_sql('name, id','employed')
    return render_template('add_empl.html', employees=employees, departments=departments)

@main.route('/add-employee', methods=['POST'])
def add_empl_post():
    manager = request.form['manager']
    if manager == 'None':
        manager = None
    data = (control_input(request.form['name']), control_input(request.form['phone_nr']), control_input(request.form['salary']), manager, request.form['department'])
    if dbh.command_sql('INSERT INTO employed (name, phone_nr, salary, manager, department) VALUES(?,?,?,?,?)', data):
        flash('A new employee has been added','success')
        return empl_list_redirect()
    abort(500)
    
# Add department
@main.route('/add-department')
def add_dept():
    return render_template('add_dept.html')

@main.route('/add-department', methods=['POST'])
def add_dept_post():
    data = (request.form['id'], control_input(request.form['name']))
    if dbh.command_sql('INSERT INTO department (dept_id, name) VALUES(?,?)', data):
        flash('A new department has been added','success')
        return dept_list_redirect()
    abort(500)

# Update employee
@main.route('/update-employee')
def update_empl():
    if 'update_empl' not in session:
        abort(401)
    empl_id = int(session['update_empl'])
    employees = dbh.select_sql('*','employed')
    exists = False
    for employee in employees:
        if empl_id == employee[0]:
            exists = True
            active_empl = employee
            employees.remove(active_empl)
    if not exists:
        flash('The employee does not exist','warning')
        return empl_list_redirect()
    employees = superiors(empl_id, employees)
    departments = dbh.select_sql('name, dept_id', 'department')
    return render_template('upd_empl.html', departments=departments, employees=employees, active_empl=active_empl)

@main.route('/update-employee', methods=['POST'])
def update_empl_post():
    if 'update_empl' not in session:
        abort(401)
    empl_id = session['update_empl']
    session.pop('update_empl', None)
    manager = request.form['manager']
    if manager == 'None':
        manager = None
    data = (control_input(request.form['name']), control_input(request.form['phone_nr']), control_input(request.form['salary']), manager, request.form['department'], empl_id)
    if not dbh.command_sql('UPDATE employed SET name=?, phone_nr=?, salary=?, manager=?, department=? WHERE id=?', data):
        abort(500)
    flash('The employee has been updated', 'success')
    return empl_list_redirect()

# Update department
@main.route('/update-department')
def update_dept():
    if 'update_dept' not in session:
        abort(401)
    department = dbh.select_with_data('SELECT * FROM department WHERE dept_id=?',(session['update_dept'],))[0]
    if not department:
        abort(500)
    return render_template('upd_dept.html', department=department)

@main.route('/update-department', methods=['POST'])
def update_dept_post():
    if 'update_dept' not in session:
        abort(401)
    dept_id = session['update_dept']
    data = (control_input(request.form['name']), dept_id)
    if dbh.command_sql('UPDATE department SET name = ? WHERE dept_id = ?', data):
        flash('The department has been updated','success')
        return dept_list_redirect()
    abort(500)

# Delete employee
@main.route('/delete-empl', methods=['DELETE'])
def delete_empl():  
    empl_id = int(request.form['id'])
    employees = dbh.select_sql('*','employed')
    if not employees:
        abort(500)
    for employee in employees:
        if empl_id == employee[0]:
            active_empl = employee
            if not upd_direct_sub(active_empl, employees):
                abort(500)
            if dbh.command_sql('DELETE FROM employed WHERE id=?',(empl_id,)):
                flash('The employee has been deleted','info')
                return 'DELETE action was successful'
            else:
                abort(500)
    flash('The employee does not exist','warning')
    return 'DELETE action was unsuccessful'

# Control value for any forbidden characters and remove them
def control_input(value):
    forbidden_chars = ['"', '(', ')', '/', '\\', '\'','-',' ', '{', '}', '[', ']', '=', '?', '.', ',', ';', ':', '_']
    for char in forbidden_chars:
        value = value.replace(char,'')
    return value

#Common redirects
def empl_list_redirect():
    return redirect(url_for('main.list_empl'))
def dept_list_redirect():
    return redirect(url_for('main.list_dept'))

# Recursive algorithm for removing any subordinates from a list of employees
# and returning only superiors or those with no manager at all
def superiors(empl_id, employees):
    for employee in employees:
        if empl_id == employee[4]:
            employees.remove(employee)
            superiors(employee[0], employees)
            superiors(empl_id, employees)
    return employees

# Update any direct subordinates to an employee that is being deleted
# so that their manager is the deleted employees manager instead of NULL 
def upd_direct_sub(active_empl, employees):
    for employee in employees:
        if employee[4] == active_empl[0]:
            if not dbh.command_sql('UPDATE employed SET manager=? WHERE id=?', (active_empl[4], employee[0])):
                return False
    return True

my_server/templates/add_dept.html
{% extends 'base.html' %}
{% set doc_title = 'Add department' %}
{% set add_dept_active = 'active' %}
{% block header %}
Add department
{% endblock header %}
{% block content %}
<form class="m-2 mt-3 p-2 border rounded row g-3 input-group" method="POST" action="">
    <div class="col-md-4">
        <label for="inputId" class="form-label">Department ID</label>
        <input type="text" class="form-control" id="inputId" name="id">
    </div>
    <div class="col-md-8">
        <label for="inputName" class="form-label">Department name</label>
        <input type="text" class="form-control" id="inputName" name="name">
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">Add department</button>
    </div>
</form>
{% endblock content %}

my_server/templates/add_empl.html
{% extends 'base.html' %}
{% set doc_title = 'Add employee' %}
{% set add_empl_active = 'active' %}
{% block header %}
Add employee
{% endblock header %}
{% block content %}
<form class="m-2 mt-3 p-2 border rounded row g-3 input-group" method="POST" action="{{url_for('main.add_empl_post')}}">
  <div class="col-12">
    <label for="inputName" class="form-label">Name</label>
    <input type="text" class="form-control" id="inputName" name="name">
  </div>
  <div class="col-md-8">
    <label for="inputNumber" class="form-label">Phone number</label>
    <input type="tel" class="form-control" id="inputNumber" name="phone_nr">
  </div>
  <div class="col-md-4">
    <label for="inputSalary" class="form-label">Salary</label>
    <input type="number" class="form-control" id="inputSalary" name="salary">
  </div>
  <div class="col-md-4">
    <label for="inputManager" class="form-label">Manager</label>
    <select id="inputManager" class="form-select" name="manager">
      <option value="None" selected>None</option>
      {% for employee in employees %}
      <option value="{{employee[1]}}">{{employee[0]}}</option>
      {% endfor %}
    </select>
  </div>
  <div class="col-md-4">
    <label for="inputDepartment" class="form-label">Department</label>
    <select id="inputDepartment" class="form-select" name="department">
      {% for department in departments %}
      <option value="{{department[1]}}">{{department[0]}}</option>
      {% endfor %}
    </select>
  </div>
  <div class="col-12">
    <button type="submit" class="btn btn-primary">Add employee</button>
  </div>
</form>
{% endblock content %}

my_server/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
  <!--Import for jQuery-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <!--Import for jquery confirm plug-in-->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
  <!-- Import for Bootstrap 5.2.2-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
  <!--Import for bootstrap alert icons-->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" viewBox="0 0 16 16">
      <path
        d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
    </symbol>
    <symbol id="info-fill" viewBox="0 0 16 16">
      <path
        d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
    </symbol>
    <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
      <path
        d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
    </symbol>
  </svg>
  <title>{{doc_title}}</title>
</head>

<body class="">
  <div class="page-header">
    <img src="{{url_for('static', filename='images/landscape.jpg')}}" class="card-img page-header-img"
      alt="landscape background-image">
    <div class="card-img-overlay">
      <h1 class="card-title page-header-text mb-auto mx-3">{% block header %}{% endblock %}</h1>
    </div>
  </div>
  <nav class="navbar navbar-expand-md sticky-top">
    <div class="px-2">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link mx-lg-2 {{index_active}}" id="start" href="{{url_for('main.index')}}">Home</a>
          <a class="nav-link mx-lg-2 {{upd_empl_active}}" id="user-list" href="{{url_for('main.list_empl')}}">Update
            employee</a>
          <a class="nav-link mx-lg-2 {{upd_dept_active}}" id="user-list" href="{{url_for('main.list_dept')}}">Update
            department</a>
          <a class="nav-link mx-lg-2 {{add_empl_active}}" id="user-list" href="{{url_for('main.add_empl')}}">Add
            employee</a>
          <a class="nav-link mx-lg-2 {{add_dept_active}}" id="user-list" href="{{url_for('main.add_dept')}}">Add
            department</a>
        </div>
      </div>
    </div>
  </nav>
  <div class="messages">
    {% for category, message in get_flashed_messages(with_categories = True) %}
    <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
      {% if category == 'warning' or 'danger' %}
      <svg class="bi flex-shrink-1 mb-1 mx-1" width="18" height="18" role="img" aria-label="Warning:">
        <use xlink:href="#exclamation-triangle-fill" />
      </svg>
      <strong>Holy guacamole!</strong> {{ message }}
      {% elif category == 'success' %}
      <svg class="bi flex-shrink-1 mb-1 mx-1" width="18" height="18" role="img" aria-label="Success:">
        <use xlink:href="#check-circle-fill" />
      </svg>
      <strong>Wohoo!</strong> {{ message }}
      {% else %}
      <svg class="bi flex-shrink-1 mb-1 mx-1" width="18" height="18" role="img" aria-label="Info:">
        <use xlink:href="#info-fill" />
      </svg>
      <strong>Woah!</strong> {{ message }}
      {% endif %}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
  </div>
  <section class="container p-3">
    {% block content %}{% endblock %}
  </section>
  <footer class="mt-auto px-2 py-1 fixed-bottom">
    <p class="footer-text text-light">Copyright <i class="bi bi-c-circle icon-font"></i> Lukas Andersson</p>
  </footer>
</body>

</html>

my_server/templates/index.html
{% extends 'base.html' %}
{% set doc_title = 'Employees' %}
{% set index_active = 'active' %}
{% block header %}
Employees
{% endblock header %}
{% block content %}
<div class="input-group w-25">
    <div class="form-floating mb-2">
        <input type="text" id="search1" class="form-control" placeholder="Search" />
        <label class="form-label" for="search1">Search</label>
    </div>
</div>
<table class="table table-striped table-hover table-bordered"
    aria-label="Employees">
    <thead>
        <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Department</th>
        </tr>
    </thead>
    <tbody id="myTable">
        {% for employee in employees %}
        <tr>
            <td>{{ employee[0] }}</td>
            <td>{{ employee[1] }}</td>
            <td>{{ employee[2] }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<script src="{{ url_for('static', filename='search.js') }}" type="text/javascript"></script>
{% endblock content %}

my_server/templates/list_dept.html
{% extends 'base.html' %}
{% set doc_title = 'Departments' %}
{% set upd_dept_active = 'active' %}
{% block header %}
Departments
{% endblock header %}
{% block content %}
<div class="input-group w-25">
    <div class="form-floating mb-2">
        <input type="search" id="search1" class="form-control" placeholder="Search"/>
        <label class="form-label" for="search1">Search</label>
    </div>
</div>
<table class="table table-striped table-hover table-bordered" aria-label="Departments">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Update department</th>
        </tr>
    </thead>
    <tbody id="myTable">
        {% for department in departments %}
        <tr>
            <td>{{ department[1] }}</td>
            <td>{{ department[0] }}</td>
            <td><button class="btn btn-primary btn-sm update-btn" data-id="{{ department[1] }}">Update</button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<script src="{{ url_for('static', filename='search.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='update.js') }}" type="text/javascript"></script>
{% endblock content %}

my_server/templates/list_empl.html
{% extends 'base.html' %}
{% set doc_title = 'Employees' %}
{% set upd_empl_active = 'active' %}
{% block header %}
Employees
{% endblock header %}
{% block content %}
<div class="input-group w-25">
    <div class="form-floating mb-2">
        <input type="search" id="search1" class="form-control" placeholder="Search" />
        <label class="form-label" for="search1">Search</label>
    </div>
</div>
<table class="table table-striped table-hover table-bordered" aria-label="Employees">
    <thead>
        <tr>
            <th>Name</th>
            <th>Department</th>
            <th>Update employee</th>
            <th>Delete employee</th>
        </tr>
    </thead>
    <tbody id="myTable">
        {% for employee in employees %}
        <tr>
            <td>{{ employee[0] }}</td>
            <td>{{ employee[1] }}</td>
            <td><button class="btn btn-primary btn-sm update-btn" data-id="{{ employee[2] }}">Update</button></td>
            <td><button class="delete btn btn-danger btn-sm" data-id="{{ employee[2] }}">Delete</button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<script src="{{ url_for('static', filename='search.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='update.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='confirm.js') }}" type="text/javascript"></script>
{% endblock content %}

my_server/templates/upd_dept.html
{% extends 'base.html' %}
{% set doc_title = 'Update department' %}
{% set upd_dept_active = 'active' %}
{% block header %}
Update department
{% endblock header %}
{% block content %}
<form class="m-2 mt-3 p-2 border rounded row g-3 input-group" method="POST" action="">
    <div class="col-md-4">
        <label for="inputId" class="form-label">Department ID</label>
        <div type="text" class="form-control" id="inputId">{{ department[0] }}</div>
    </div>
    <div class="col-md-8">
        <label for="inputName" class="form-label">Department name</label>
        <input type="text" class="form-control" id="inputName" name="name" value="{{ department[1] }}">
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">Update department</button>
    </div>
</form>
{% endblock content %}

my_server/templates/upd_empl.html
{% extends 'base.html' %}
{% set doc_title = 'Update employee' %}
{% set upd_empl_active = 'active' %}
{% block header %}
Update employee
{% endblock header %}
{% block content %}
<h2 id="active_empl" data-manager-id="{{ active_empl[4] }}" data-department-id="{{ active_empl[5] }}">Update {{ active_empl[1] }}</h2>
<form class="m-2 mt-3 p-2 border rounded row g-3 input-group" method="POST" action="">
    <input type="hidden" name="empl_id" value="{{ active_empl[0] }}">
    <div class="col-12">
        <label for="inputName" class="form-label">Name</label>
        <input type="text" class="form-control" id="inputName" name="name" value="{{ active_empl[1] }}">
    </div>
    <div class="col-md-8">
        <label for="inputNumber" class="form-label">Phone number</label>
        <input type="tel" class="form-control" id="inputNumber" name="phone_nr" value="{{ active_empl[2] }}">
    </div>
    <div class="col-md-4">
        <label for="inputSalary" class="form-label">Salary</label>
        <input type="number" class="form-control" id="inputSalary" name="salary" value="{{ active_empl[3] }}">
    </div>
    <div class="col-md-4">
        <label for="inputManager" class="form-label">Manager</label>
        <select id="inputManager" class="form-select" name="manager">
            <option class="manager" value="None">None</option>
            {% for employee in employees %}
            <option class="manager" value="{{employee[0]}}">{{employee[1]}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="col-md-4">
        <label for="inputDepartment" class="form-label">Department</label>
        <select id="inputDepartment" class="form-select" name="department">
            {% for department in departments %}
            <option class="department" value="{{department[1]}}">{{department[0]}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">Update employee</button>
    </div>
</form>
<script src="{{ url_for('static', filename='selected.js') }}"></script>
{% endblock content %}